//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Экзамен
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Form_release { get; set; }
        public string Dosage { get; set; }
        public string Manufacturer { get; set; }
        public string Shelf_life { get; set; }
    }
}
